### ISSUE TITLE
CSV/TSV convenience variables

### ISSUE THREAD

**Issue by Tyler-Hardin** [ezrosent/frawk#100]
It would be really nice to have `$column_name` work for csv and tsv. Could this be added?

**Comment by ezrosent** [comment]
so we unfortunately can't do `$column_name` as that's perfectly valid awk (`x=1; print $x` works like `print 1`), and it's a common-enough idiom that I don't think it makes sense to change the syntax.

I did add the -H option a while back which should help.  see #31 for more context.
