### ISSUE TITLE
Minor benchmark note

### ISSUE THREAD

**Issue by jondegenhardt** [ezrosent/frawk#16]
Hi. Primary `tsv-utils` author here.

First, I want to congratulate you on the project work. Haven't tried it yet, but looking through the documentation, it looks really well thought out. There have been multiple attempts to improve Awk performance over the years. This looks like a winner on the performance front, with CSV support built-in. Very nice!

Also very much appreciate that `tsv-utils` is included in the benchmark suite. A very minor thing - The `csv2tsv` tool mentioned in the benchmark doc has had some significant performance improvements in the latest releases (2.1.0, 2.1.1). 40-60% faster depending on the nature of CSV-escaping used in the input files. The improvement won't change the conclusion in the report: that a running a CSV aware tool will be faster than converting CSV to TSV and passing to a TSV aware tool. But, the performance improvements do make the conversion more palatable.

Again, congrats on some really nice work!

--Jon

**Comment by ezrosent** [comment]
Hi Jon, 
Thanks for reaching out, and for the kind words. I hope it comes across in the documentation, but I'd just like to say that I really admire the work you've done with `tsv-utils`.  I downloaded 2.1.1 and found that it is indeed much faster; nice work!

```
$ time ./tsv-utils-v2.1.1_osx-x86_64_ldc2/bin/csv2tsv all_train.csv > all_train.tsv
./tsv-utils-v2.1.1_osx-x86_64_ldc2/bin/csv2tsv all_train.csv > all_train.tsv  8.40s user 5.85s system 97% cpu 14.577 total
$ time ./tsv-utils-v2.1.1_osx-x86_64_ldc2/bin/csv2tsv TREE_GRM_ESTN.csv > TREE_GRM_ESTN.tsv
./tsv-utils-v2.1.1_osx-x86_64_ldc2/bin/csv2tsv TREE_GRM_ESTN.csv >   20.32s user 8.08s system 99% cpu 28.654 total
```

[This change](https://github.com/ezrosent/frawk/commit/7129c3b7ba67ab6f899eae92fece141499386278) adds those times in. Please leave a comment here or open a new issue if I missed something.

**Comment by jondegenhardt** [comment]
That's great, appreciate you making the change, thanks! And yes, very clear from the writing you saw value in what has been done with `tsv-utils`.
