### ISSUE TITLE
stdout buffering

### ISSUE THREAD

**Issue by sstadick** [ezrosent/frawk#18]
Hi! Super cool project!

I was looking at your io related code an noticed you are using `std::io::stdout`, which has issues: https://github.com/rust-lang/rust/issues/60673

I've worked around this in other libraries of my own by using burtsushi's https://docs.rs/grep-cli/0.1.5/grep_cli/, which provides a correctly buffering stdout method when piping to a file, and line buffering when connected to a TTY. 

I've seen significant speedups in my own libraries switching to buffered stdout. This may help close the single threaded gap with tsv utils.

**Comment by ezrosent** [comment]
Hey, thanks for this pointer! It does indeed look like I should be using this. To set expectations on this improving benchmarks, though, all writes are batched in a local thread and then sent to a background thread to be issued. Beyond that, the background thread uses write_all_vectored, which lets you write a whole batch without necessarily flushing after each line if I'm reading the LineBuffered implementation correctly. 

Still, like I said I still think frawk should be using `grep_cli`; so I'll keep this open until I migrate.
