### ISSUE TITLE
Other awks don't print trailing zeros when printing floats.

### ISSUE THREAD

**Issue by ghuls** [ezrosent/frawk#41]
Other awks don't print trailing zeros when printing floats.
This feature would be great to have in frawk too as now when adding an integer value to a column which contained an integer will give you back a float which is quite annoying in my usecase.

I have for example BED files with chromosomal coordinates in column 2 and 3.
```
chr1	1000	2000	...
```

Like shown here, those intervals are extended:
https://github.com/ghuls/extendBed/blob/master/extendBed.sh

Test case:
```bash
for AWK in frawk gawk mawk; do
    echo "${AWK}:";
    echo '1 9.0 5.5 6.600' | ${AWK} '
        BEGIN { OFS="\t" }
        {
            print "column 1:", $1, $1 + 0, 0 + $1, $1 + 1.0;
            print "column 2:", $2, $2 + 0, 0 + $2, $2 + 1.0;
            print "column 3:", $3, $3 + 0, 0 + $3, $3 + 0.5;
            print "column 4:", $4, $4 + 0, 0 + $4, $4 + 0.4;
        }';
    echo;
done

frawk:
column 1:	1	1.0	1.0	2.0
column 2:	9.0	9.0	9.0	10.0
column 3:	5.5	5.5	5.5	6.0
column 4:	6.600	6.6	6.6	7.0

gawk:
column 1:	1	1	1	2
column 2:	9.0	9	9	10
column 3:	5.5	5.5	5.5	6
column 4:	6.600	6.6	6.6	7

mawk:
column 1:	1	1	1	2
column 2:	9.0	9	9	10
column 3:	5.5	5.5	5.5	6
column 4:	6.600	6.6	6.6	7
```

**Comment by ezrosent** [comment]
I think this is a reasonable ask. I initially thought this was going to make the semantics more explicit, but I've also found it annoying using frawk day to day. I'll see about (a) modifying what ryu is doing when the float has an exact integer representation (b) special-casing floating point rendering for this setting or (c) migrating to a different float rendering library/algorithm. I'm thinking (b), as checking if a float can be represented exactly as an integer is pretty cheap, and (e.g.) [dtoa](https://github.com/dtolnay/dtoa), while potentially interesting on its own, seems to also append ".0" in the same cases.

**Comment by ghuls** [comment]
It might be worth to open a feature request to allow stripping all trailing zeros for those crates.

**Comment by ezrosent** [comment]
I'm closing this PR in light of #44, thanks for the contribution!
