### ISSUE TITLE
Allow more than one `-f` argument

### ISSUE THREAD

**Issue by ghuls** [ezrosent/frawk#47]
Allow more than one `-f` argument. Now it results in this error message:

```error: The argument '--program-file <FILE>' was provided more than once, but cannot be used multiple times```

**Comment by ezrosent** [comment]
I've never done this before! This shouldn't be too bad. Thanks for filing the issue.

**Comment by ghuls** [comment]
Multiple -f are used when you have a awk library file and the actual program.

**Comment by ezrosent** [comment]
I believe this is done now!
