### ISSUE TITLE
upgade llvm? llvm10 is EOL

### ISSUE THREAD

**Issue by motiejus** [ezrosent/frawk#67]
Since llvm10 is EOL now (as of writing, only [11+ are available](https://apt.llvm.org/bullseye/pool/main/l/)), can frawk update it's LLVM dependency, or perhaps document an easier way to find llvm10?

**Comment by ezrosent** [comment]
Thanks for pointing this out, and will do! I think LLVM 10 should still be fairly accessible and I will update the docs if I find updating to 12 will take too long. My hope is that updating to 12 should not be terribly difficult though. I'll try to follow up soon.

**Comment by ezrosent** [comment]
I've published frawk 0.4.4 on cargo, which now depends on LLVM 12
