### ISSUE TITLE
Support `exit`

### ISSUE THREAD

**Issue by ghuls** [ezrosent/frawk#71]
> `exit  opt_expr`
> An exit statement causes immediate execution of the END actions or program termination if there are none or if the exit occurs in an END action.  The opt_expr sets the exit value of the program unless overridden by a later exit or subsequent error.

```bash
❯ seq 1 10 | mawk '{ print $0; if ($1 >= 8) { last = $0; exit 33; } } END { print "last line before exit: " last;}' ; echo "Exit code: $?";
1
2
3
4
5
6
7
8
last line before exit: 8
Exit code: 33

❯ seq 1 10 | frawk '{ print $0; if ($1 >= 8) { last = $0; exit 33; } } END { print "last line before exit: " last;}' ; echo "Exit code: $?";
1
2
3
4
5
6
7
8
9
10
last line before exit: 10
Exit code: 0


# Same but with exit with extra parentheses (frawk does not remove extra (), (print had this issue too in the past)):

❯ seq 1 10 | mawk '{ print $0; if ($1 >= 8) { last = $0; exit(33); } } END { print "last line before exit: " last;}' ; echo "Exit code: $?";
1
2
3
4
5
6
7
8
last line before exit: 8
Exit code: 33

❯ seq 1 10 | frawk '{ print $0; if ($1 >= 8) { last = $0; exit(33); } } END { print "last line before exit: " last;}' ; echo "Exit code: $?";
failed to create program context: [src/cfg.rs:1641:21] Call to unknown function "exit"
Exit code: 1

```

**Comment by ezrosent** [comment]
Thanks for the test cases! Totally agree this should be supported. I think most of the necessary work for this is in place. The only issue I can think of is the semantics of `exit` for parallel scripts. I think it should be reasonable, if one thread exits with `1` and another exits with `2` to pick an arbitrary non-zero exit code as the result of the entire script.

**Comment by ghuls** [comment]
I didn't use the parallel option yet, but wouldn't it make sense to use the exit code value from the first thread that produces a non-zero value and discard all output from all other threads that processed data from after the chunk processed by that thread?

```
chunk 1 -> thread 1
chunk 2 -> thread 2
chunk 3 (code will produce exit code 1 for a certain line)-> thread 3
chunk 4 -> thread 4
chunk 5 -> thread 5
```

Output:
```
thread 1 output
thread 2 output
thread 3 output till exit code

exit code 1
```

**Comment by ezrosent** [comment]
Sure! I think picking "first" would also work. I'll start with single-threaded support and then get to work on the multi-threaded case.

**Comment by ezrosent** [comment]
I think I've got multithreaded exit working on the `add_exit` branch. I just need to add some tests; hopefully I'll merge it this weekend.

**Comment by ezrosent** [comment]
Closing given that #77 has been merged. I'll push a new version to crates.io soon
