### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by ethancedwards8** [ezrosent/frawk#76]
Hi,

I'm trying to package frawk for nixos/nixpkgs, but I cannot do that without a Cargo.lock package. Are there any reasons why one isn't included? Thanks.

**Comment by ezrosent** [comment]
nope! I'll add one this week. Thanks for filing the issue!

**Comment by ethancedwards8** [comment]
Yup! Also, is this repo participating in Hacktoberfest?

**Comment by ezrosent** [comment]
That latest commit should hopefully fix things.

As for Hacktoberfest, it is not. Though I'll admit I don't think I'd heard of it before you mentioned it. I'll be sure to read up on it, though I'll admit that I have been pretty busy lately..

**Comment by ethancedwards8** [comment]
Hacktoberfest is nothing more than a contest held by Intel, DigitalOcean, and other big names that encourages people to contribute to Open Source projects. Afaik, all you have to do is add the Hacktoberfest tag to the repository, and add the Hacktoberfest-accepted tag to any accepted PRs and merge them. 

Anyway, if frawk participates in it that'd be cool, if not that's cool too.

**Comment by ezrosent** [comment]
I may look into it next year, thanks for the pointer though! Closing this issue as Cargo.lock is now checked in.
