### ISSUE TITLE
Prefer name "sqawk" and have a bird logo

### ISSUE THREAD

**Issue by crisdosyago** [ezrosent/frawk#86]
Or keep frawk and have a bird / dinosaur logo.

**Comment by hustcer** [comment]
[`sqawk`](https://github.com/dbohdan/sqawk) has been taken, some other name?

**Comment by crisdosyago** [comment]
wawk

tawk

kwawk

kwa

Urukhai

**Comment by ehiggs** [comment]
ripawk

**Comment by hustcer** [comment]
I like `tawk` or even `oak`？

**Comment by crisdosyago** [comment]
woah oak is different. But if people like that, if that's what you're going for, then go with it. But I like the plays on awk thing...I think `oak` sounds like `awk` only in some accents: Scottish maybe?

hawk is not a bad one too ;p ;) xx ;p

**Comment by hustcer** [comment]
hawk is cool，but there is a similar tool：https://github.com/gelisam/hawk

**Comment by crisdosyago** [comment]
Yeah lots of names are taken: https://github.com/search?q=oak

But it's OK. We just got to pick one.
