### ISSUE TITLE
Plans for a new release? Last release was 1.5 years ago.

### ISSUE THREAD

**Issue by yurivict** [ezrosent/frawk#95]

**Comment by ezrosent** [comment]
Hi! I haven't been posting regular releases, though I tend to push to crates.io every time there's an update; I just pushed a new version prompted by this issue.

My reason for this is that I was never able to build a standalone binary that had LLVM or SIMD intrinsics properly supported; as a result, building from source via `cargo install` was often just a better bet for most people.

**Comment by yurivict** [comment]
But there is no new tag in this repository.

**Comment by ezrosent** [comment]
Happy to make a new tag; is it alright if it doesn't have a binary linked?

**Comment by yurivict** [comment]
It's ok.

**Comment by ezrosent** [comment]
Pushed [0.4.7](https://github.com/ezrosent/frawk/releases/tag/v0.4.7)
